#spring.profiles.active: @spring.profiles.active@
spring:
  profiles.active: development

---
spring:
  profiles: development
  h2:
    location: ./target/jmsexp
    console:
      enabled: true
      path: /db
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:./target/devDB;DB_CLOSE_ON_EXIT=FALSE;MV_STORE=FALSE;MVCC=FALSE
  jpa:
    database-platform: H2
    generate-ddl: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        use-new-id-generator-mappings: true
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    show-sql: true

brokerUrl: tcp://localhost:61616
orderQueue: order-queue

logging:
  file: ./target/jmsexp.log
  level: debug

flyway:
  user: sa
  password:
