spring:
  profiles.active: development-h2

---
spring:
  profiles: development-h2
  h2:
    location: ./target/jmsexp
    console:
      enabled: true
      path: /db
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:./target/authDevDB;DB_CLOSE_ON_EXIT=FALSE;MV_STORE=FALSE;MVCC=FALSE
  jpa:
    database-platform: H2
    generate-ddl: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        use-new-id-generator-mappings: true
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    show-sql: false
flyway:
  locations: classpath:/db/migration/H2
  user: sa
  password:
  enabled: true
server:
  port: ${port:8085}
---