    create table auth.sec_app_user (
        id decimal(19,2) generated by default as identity,
        password varchar(255),
        username varchar(255)
    );
    create table auth.user_role (
        role varchar(255) not null,
        app_user_id bigint not null,
        sec_app_user_id decimal(19,2)
    );

